drop table if exists users;
create table users
(
    user_key bigint generated by default as identity,
    name     varchar(255),
    email    varchar(255)
);
alter table users
    add constraint users_uk_01 unique (email);
